### ISSUE TITLE
Rename evmc_context to evmc_host_context or evmc_host

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#215]

**Comment by jakelang** [comment]
I think calling it `evmc_host_context` wouldn't really make sense, just harder to type and doesn't convey any extra meaning.
I personally think it is ok as it is right now, but `evmc_host` would be my choice if we were to change it.

**Comment by chfast** [comment]
I'm rather for `evmc_host_context` because it suggest it is some data (not interface) and opaque (like OpenGL context, etc).

This is rather to fix the current bad name. Bigger issue (to be handled separately) is to separate host interface from host context pointer. And figure out naming for 4 concepts:
- host interface (in OOP sense),
- abstract host class for Client implementations,
- host class for VM implementations,
- host context pointer.
