### ISSUE TITLE
Modules or Plugins?

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#219]
Question about naming: The loadable EVMC VMs should be called "EVMC Modules" or "EVMC Plugins"?

**Comment by jakelang** [comment]
I think that "plugin" has the connotation of being more like a loadable feature or modification. Module is nice, but also sounds like it's a component of EVM-C rather than a VM connected through it.
Linux kernel calls the loadable drivers and other extensions "Modules", though, so I think the connotation isn't really that strong.
